// Generated by generate_cpp.py
// Do not edit manually!

#include <irata/asm/asm.hpp>
#include <vector>

namespace irata::asm_ {
const std::vector<Instruction> instruction_table = {

Instruction{
    .name = "LDA",
    .opcode = 169,
    .addressing_mode = AddressingMode::IMMEDIATE,
    .description = "Load accumulator from constant",
},

Instruction{
    .name = "LDA",
    .opcode = 173,
    .addressing_mode = AddressingMode::ABSOLUTE,
    .description = "Load accumulator from memory",
},

Instruction{
    .name = "STA",
    .opcode = 133,
    .addressing_mode = AddressingMode::IMMEDIATE,
    .description = "Store accumulator into memory",
},

Instruction{
    .name = "STA",
    .opcode = 141,
    .addressing_mode = AddressingMode::ABSOLUTE,
    .description = "Store accumulator into memory",
},

};
}
