// Generated by generate_cpp.py
// Do not edit manually!

#include <irata/asm/instruction.hpp>
#include <vector>

namespace irata::asm_ {

const std::set<Instruction>& Instruction::irata() {
    static const std::set<Instruction> instruction_table = {
        
        Instruction(
            "LDA",
            0xA9,
            AddressingMode::IMMEDIATE,
            "Load accumulator from constant"
        ),
    };
    return instruction_table;
}

} // namespace irata::asm_
