# CMake generated Testfile for 
# Source directory: /home/runner/workspace/irata/test
# Build directory: /home/runner/workspace/irata/build_nosani/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(run_adc "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/adc.cartridge")
set_tests_properties(run_adc PROPERTIES  DEPENDS "adc_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_and "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/and.cartridge")
set_tests_properties(run_and PROPERTIES  DEPENDS "and_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_asl "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/asl.cartridge")
set_tests_properties(run_asl PROPERTIES  DEPENDS "asl_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_dex "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/dex.cartridge")
set_tests_properties(run_dex PROPERTIES  DEPENDS "dex_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_dey "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/dey.cartridge")
set_tests_properties(run_dey PROPERTIES  DEPENDS "dey_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_eor "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/eor.cartridge")
set_tests_properties(run_eor PROPERTIES  DEPENDS "eor_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_hlt "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/hlt.cartridge")
set_tests_properties(run_hlt PROPERTIES  DEPENDS "hlt_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_inx "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/inx.cartridge")
set_tests_properties(run_inx PROPERTIES  DEPENDS "inx_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_iny "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/iny.cartridge")
set_tests_properties(run_iny PROPERTIES  DEPENDS "iny_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_jeq "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/jeq.cartridge")
set_tests_properties(run_jeq PROPERTIES  DEPENDS "jeq_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_jmp "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/jmp.cartridge")
set_tests_properties(run_jmp PROPERTIES  DEPENDS "jmp_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_jsr "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/jsr.cartridge")
set_tests_properties(run_jsr PROPERTIES  DEPENDS "jsr_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_lda "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/lda.cartridge")
set_tests_properties(run_lda PROPERTIES  DEPENDS "lda_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_ldx "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/ldx.cartridge")
set_tests_properties(run_ldx PROPERTIES  DEPENDS "ldx_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_ldy "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/ldy.cartridge")
set_tests_properties(run_ldy PROPERTIES  DEPENDS "ldy_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_lsr "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/lsr.cartridge")
set_tests_properties(run_lsr PROPERTIES  DEPENDS "lsr_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_ora "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/ora.cartridge")
set_tests_properties(run_ora PROPERTIES  DEPENDS "ora_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_pha "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/pha.cartridge")
set_tests_properties(run_pha PROPERTIES  DEPENDS "pha_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_php "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/php.cartridge")
set_tests_properties(run_php PROPERTIES  DEPENDS "php_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_phx "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/phx.cartridge")
set_tests_properties(run_phx PROPERTIES  DEPENDS "phx_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_phy "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/phy.cartridge")
set_tests_properties(run_phy PROPERTIES  DEPENDS "phy_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_rol "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/rol.cartridge")
set_tests_properties(run_rol PROPERTIES  DEPENDS "rol_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_ror "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/ror.cartridge")
set_tests_properties(run_ror PROPERTIES  DEPENDS "ror_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_sbc "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/sbc.cartridge")
set_tests_properties(run_sbc PROPERTIES  DEPENDS "sbc_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_sta "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/sta.cartridge")
set_tests_properties(run_sta PROPERTIES  DEPENDS "sta_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_stx "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/stx.cartridge")
set_tests_properties(run_stx PROPERTIES  DEPENDS "stx_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_sty "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/sty.cartridge")
set_tests_properties(run_sty PROPERTIES  DEPENDS "sty_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_tax "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/tax.cartridge")
set_tests_properties(run_tax PROPERTIES  DEPENDS "tax_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
add_test(run_tay "sh" "-c" "/home/runner/workspace/irata/build_nosani/sim/sim < /home/runner/workspace/irata/build_nosani/test/tay.cartridge")
set_tests_properties(run_tay PROPERTIES  DEPENDS "tay_asm" _BACKTRACE_TRIPLES "/home/runner/workspace/irata/test/CMakeLists.txt;16;add_test;/home/runner/workspace/irata/test/CMakeLists.txt;0;")
